name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 1. Chocolatey를 사용하여 Tesseract와 Ghostscript 설치
    - name: Install Tesseract and Ghostscript via Chocolatey
      run: |
        choco install tesseract ghostscript -y

    # 2. Tesseract가 설치된 경로를 PATH에 추가
    #    Tesseract는 기본적으로 C:\Program Files\Tesseract-OCR에 설치됩니다.
    #    $env:PATH += ";C:\Program Files\Tesseract-OCR" 명령어를 통해 현재 세션의 PATH를 업데이트
    - name: Add Tesseract and Ghostscript to PATH
      run: |
        echo "C:\Program Files\Tesseract-OCR" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
        # Ghostscript 설치 경로를 동적으로 찾아 PATH에 추가
        Get-ChildItem "C:\Program Files\gs" | Where-Object {$_.PSIsContainer} | Select-Object -First 1 | ForEach-Object {
          $gsPath = Join-Path $_.FullName "bin"
          echo $gsPath | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        }
        
    # 3. 설치 및 PATH 추가 확인
    - name: Verify Tesseract and Ghostscript installation
      run: |
        tesseract --version
        
        # Ghostscript 실행 파일 확인
        if (Get-Command gswin64c.exe -ErrorAction SilentlyContinue) {
            gswin64c.exe --version
        } else {
            Write-Host "Ghostscript executable not found in PATH."
            exit 1
        }
    
    # 4. ocrmypdf를 먼저 설치해서 시스템 종속성을 찾도록 함
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ocrmypdf
        pip install pyinstaller pandas openpyxl xlsxwriter requests pdfplumber camelot-py[cv]

    # 5. PyInstaller로 .exe 파일 빌드
    - name: Build the EXE
      env:
        TESSDATA_PREFIX: "C:\\Program Files\\Tesseract-OCR\\tessdata"
        DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
      run: |
        pyinstaller --onefile --console --name "PDF_Translator" --add-data "C:\Program Files\Tesseract-OCR\tessdata;tessdata" test.py

    # 6. 생성된 .exe 파일을 아티팩트로 업로드
    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF-Translator-EXE
        path: dist/PDF_Translator.exe